### PR TITLE
Improve for Pull #8366 

### PR DESCRIPTION
**Pull request by Fedik**
Changes what I talked, 
about parse the options :wink: 

Still hardcoded, but at least the result more predictable.

### CODE REVIEW

**Comment by dgt41** [comment]
Thanks @Fedik, but I am getting an error: 'TypeError: undefined is not an object (evaluating 'window.size.x')'

**Comment by Fedik** [comment]
ah :hankey:  ... `window.getSize()` is mootools stuff hahaha
I have missed this part ...
hm, no idea then, sorry

**Comment by Fedik** [comment]
so, got an idea
if you find where to place 
```javascript
window.getSize = window.getSize || function(){
 return {x: jQuery(window).width(), y: jQuery(window).height() };
};
```
then it could work :wink:

**Comment by Fedik** [comment]
or wait ...

**Comment by Fedik** [comment]
ok, check now

**Pull request closed without merging**
