### PR TITLE
JoomlaCalendar.prototype

### PR DESCRIPTION
**Pull request by Fedik**
It is what I meant 😉

### CODE REVIEW

**Comment by Fedik** [comment]
hm, but I guess I broke something with `this._documentClick` it always called before `this._dayMouseDown`

**Comment by Fedik** [comment]
ok, fixed

**Comment by dgt41** [comment]
Nice, thanks! One question why did you remove the `jQuery(value).chosen('destroy');` this was creating problem on some browsers and the select tags get replaced and then are useless... ?

**Comment by Fedik** [comment]
there is hack for it https://github.com/dgt41/joomla-cms/pull/37/files#diff-282ea668781e138579e5814fd9735352R635

when `<select>` has `data-chosen="true"` then chosen.js  will think that Chosen already there, so will ignore this element 😄

**Comment by dgt41** [comment]
That didn't work for me 😕

**Comment by Fedik** [comment]
hm strange, I did not got any chosen.js problem,
maybe need `part.setAttribute('data-chosen', true);`,  
we have same hack in Access rule field,

**Comment by dgt41** [comment]
maybe safari's js engine is weird?

**Pull request merged**
